# Generated by Django 2.1.7 on 2019-04-11 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mton', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ('name',)},
        ),
    ]
